image: registry.gitlab.com/kitsune_other/kitsune_docker_unittest:0.1.0

build:
  script:
    - echo Working on branch $CI_COMMIT_REF_NAME

    - apt-get install -y libboost-filesystem-dev

    - cd /builds/tobiasanker/libKitsunePersistence
    - ./build.sh

    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:'/builds/tobiasanker/result'
    - /builds/tobiasanker/build/libKitsunePersistence/tests/tests

  tags:
    - docker
